### ISSUE TITLE
Fix readme 

### ISSUE THREAD

**Issue by shafali731** [PGreatness/import-Greatness#3]
use the requirements doc instead of telling them to install stuff one by one. Also italicize bugoul

**Comment by PGreatness** [comment]
Issue resolved. README has been updated to include section on downloading via the [requirements.txt](../master/requirements.txt) file. You can see the updated sections [here](../commit/cd759a8d0f0a64863999db641a275eab49696a24) or the markdown version [here](../blob/master/README.md).
For future reference, "Bugle" is spelled as so and not definitely not as "bugoul". Considering how the application itself is contained within a folder labelled "The Daily Bugle", may I recommend Grammarly?
